# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi_calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.FloatField()),
                ('ip', models.CharField(max_length=40)),
            ],
        ),
    ]
